//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterviewB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAIN_INFO
    {
        public decimal STD_NO { get; set; }
        public decimal STD_KIND_CODE { get; set; }
        public string STD_KIND { get; set; }
        public string STD_NAME { get; set; }
        public string NATIONAL_ID { get; set; }
        public Nullable<System.DateTime> BIRTH_DATE { get; set; }
        public Nullable<System.DateTime> CALCDATE { get; set; }
        public Nullable<short> PLACE_CODE { get; set; }
        public string PLACE { get; set; }
        public Nullable<decimal> SCN_CODE { get; set; }
        public string SCN { get; set; }
        public Nullable<decimal> SHOPA_CODE { get; set; }
        public string SHOPA { get; set; }
        public string SCN_NAME { get; set; }
        public Nullable<decimal> PERS { get; set; }
        public Nullable<decimal> COLLEGE_CODE { get; set; }
        public string COLLEGE { get; set; }
        public Nullable<decimal> GRADUATION_CODE { get; set; }
        public string GRADUATION { get; set; }
        public Nullable<decimal> POST_GRADUATION_CODE { get; set; }
        public string POST_GRADUATION { get; set; }
        public Nullable<decimal> GRADE_CODE { get; set; }
        public string GRADE { get; set; }
        public Nullable<short> SEMA_CODE { get; set; }
        public string SEMA_DATA { get; set; }
        public Nullable<short> MARY_DEG_CODE { get; set; }
        public string MARY_DEG_DATA { get; set; }
        public Nullable<short> SECURITY_CODE { get; set; }
        public string SECURITY_DATA { get; set; }
        public Nullable<short> MEDICAL_STATUS_CODE { get; set; }
        public string MEDICAL_STATUS { get; set; }
        public Nullable<decimal> LENGTH { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public Nullable<short> VISION_CODE { get; set; }
        public string VISION { get; set; }
        public Nullable<decimal> VISION_DEGREE { get; set; }
        public Nullable<short> GLASSES_CODE { get; set; }
        public string GLASSES { get; set; }
        public string FATHER_GRAD_BIRTH { get; set; }
        public string FAHER_JOB_BIRTH { get; set; }
        public string FATHER_GRAD_NOW { get; set; }
        public string FATHER_JOB_NOW { get; set; }
        public string MOTHER_NAME { get; set; }
        public string MOTHER_GRAD_NOW { get; set; }
        public string MOTHER_JOB_NOW { get; set; }
        public Nullable<decimal> SWIM_CODE { get; set; }
        public string SWIM { get; set; }
        public Nullable<decimal> SWIM_DEG { get; set; }
        public Nullable<decimal> OKLA { get; set; }
        public Nullable<decimal> OKLA_DEG { get; set; }
        public Nullable<decimal> PUSH { get; set; }
        public Nullable<decimal> PUSH_DEG { get; set; }
        public Nullable<decimal> BATN { get; set; }
        public Nullable<decimal> BATN_DEG { get; set; }
        public Nullable<decimal> RUN_100 { get; set; }
        public Nullable<decimal> RUN_100DEG { get; set; }
        public Nullable<decimal> BALANCE { get; set; }
        public Nullable<decimal> BALANCE_DEG { get; set; }
        public Nullable<decimal> RUN_1500 { get; set; }
        public Nullable<decimal> RUN_1500DEG { get; set; }
        public Nullable<decimal> SPORT_TOTAL { get; set; }
        public Nullable<decimal> SCN_TEST_A { get; set; }
        public Nullable<decimal> SCN_TEST_E { get; set; }
        public Nullable<decimal> LANG_TEST { get; set; }
        public Nullable<decimal> NOZOM_TEST { get; set; }
        public Nullable<decimal> GAM_MATH { get; set; }
        public Nullable<decimal> GAM_PH { get; set; }
        public string FATHER_NAME { get; set; }
        public string NOTES { get; set; }
    }
}
