//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterviewB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICAL_DETAILS
    {
        public decimal STD_NO { get; set; }
        public decimal STD_KIND_CODE { get; set; }
        public string STD_KIND { get; set; }
        public string STD_NAME { get; set; }
        public string NATIONAL_ID { get; set; }
        public short LAGNA_CODE { get; set; }
        public string LAGNA { get; set; }
        public Nullable<short> LAGNA_STATUS_CODE { get; set; }
        public string LAGNA_STATUS { get; set; }
        public string REMARK { get; set; }
    }
}
