//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterviewB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICAL_INFO
    {
        public decimal STD_NO { get; set; }
        public decimal STD_KIND_CODE { get; set; }
        public string STD_KIND { get; set; }
        public string STD_NAME { get; set; }
        public string NATIONAL_ID { get; set; }
        public Nullable<short> MEDICAL_STATUS_CODE { get; set; }
        public string MEDICAL_STATUS { get; set; }
        public Nullable<decimal> LENGTH { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public Nullable<short> VISION_CODE { get; set; }
        public string VISION { get; set; }
        public Nullable<decimal> VISION_DEGREE { get; set; }
        public Nullable<short> GLASSES_CODE { get; set; }
        public string GLASSES { get; set; }
    }
}
