//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterviewB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NAFSI_DETAILS
    {
        public decimal STD_NO { get; set; }
        public decimal STD_KIND_CODE { get; set; }
        public string STD_KIND { get; set; }
        public string STD_NAME { get; set; }
        public string NATIONAL_ID { get; set; }
        public Nullable<decimal> N1_CODE { get; set; }
        public string N1 { get; set; }
        public decimal DIM_CODE { get; set; }
        public string DIM_NAME { get; set; }
        public Nullable<decimal> DIM_DEG { get; set; }
        public string DIM_LEVEL { get; set; }
        public Nullable<decimal> DIM_LEVEL_CODE { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
    }
}
