//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterviewB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARENTS_INFO
    {
        public decimal STD_NO { get; set; }
        public decimal STD_KIND_CODE { get; set; }
        public string STD_KIND { get; set; }
        public string STD_NAME { get; set; }
        public string NATIONAL_ID { get; set; }
        public string FATHERGRADB { get; set; }
        public string FAHERJOBB { get; set; }
        public string FATHERGRADN { get; set; }
        public string FATHERJOBN { get; set; }
        public string MOTHERNAME { get; set; }
        public string MOTHERGRADN { get; set; }
        public string MOTHERJOBN { get; set; }
    }
}
