//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterviewB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPORT_INFO
    {
        public decimal STD_NO { get; set; }
        public decimal STD_KIND_CODE { get; set; }
        public string STD_KIND { get; set; }
        public string STD_NAME { get; set; }
        public string NATIONAL_ID { get; set; }
        public Nullable<decimal> SWIM_CODE { get; set; }
        public string SWIM { get; set; }
        public Nullable<decimal> SWIM_DEG { get; set; }
        public Nullable<decimal> OKLA { get; set; }
        public Nullable<decimal> OKLA_DEG { get; set; }
        public Nullable<decimal> PUSH { get; set; }
        public Nullable<decimal> PUSH_DEG { get; set; }
        public Nullable<decimal> BATN { get; set; }
        public Nullable<decimal> BATN_DEG { get; set; }
        public Nullable<decimal> RUN_100 { get; set; }
        public Nullable<decimal> RUN_100DEG { get; set; }
        public Nullable<decimal> BALANCE { get; set; }
        public Nullable<decimal> BALANCE_DEG { get; set; }
        public Nullable<decimal> RUN_1500 { get; set; }
        public Nullable<decimal> RUN_1500DEG { get; set; }
        public Nullable<decimal> SPORT_TOTAL { get; set; }
    }
}
