//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterviewB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<short> PRIORITY { get; set; }
        public string DESCRIPTION { get; set; }
        public string CONNECTIONID { get; set; }
    }
}
