// <auto-generated />
namespace InterviewB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changeattributesacceptdefaultvalues : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeattributesacceptdefaultvalues));
        
        string IMigrationMetadata.Id
        {
            get { return "202011261303571_change-attributes-accept-default-values"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
