// <auto-generated />
namespace InterviewB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changeattributesTOacceptdefaultvalues : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeattributesTOacceptdefaultvalues));
        
        string IMigrationMetadata.Id
        {
            get { return "202011261339137_change-attributes-TO-accept-default-values"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
