// <auto-generated />
namespace InterviewB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addPsychologicaltostudent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addPsychologicaltostudent));
        
        string IMigrationMetadata.Id
        {
            get { return "202011241425238_add-Psychological-to-student"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
